### ISSUE TITLE
频道回复之前的消息显示有问题

### ISSUE THREAD

**Issue by PBnicad** [ccbikai/BroadcastChannel#17]
![image](https://github.com/user-attachments/assets/d7784bc9-8aef-4733-8609-01174aae977a)
![image](https://github.com/user-attachments/assets/7ea927d8-7efd-4b06-a940-e13ed2175401)

**Comment by ccbikai** [comment]
麻烦提供下频道地址

**Comment by PBnicad** [comment]
https://tg.nicad.top/

**Comment by ccbikai** [comment]
请检查下最新代码是否已经修复，如果修复可以关闭 issue 了
