### ISSUE TITLE
部署成功以后页面不展示频道内容

### ISSUE THREAD

**Issue by ZhaoTim** [ccbikai/BroadcastChannel#2]
你好，首先这个项目我认为很棒，我很感兴趣，所以我尝试进行了部署，但是部署成功以后页面没有展示我在频道展示的内容，不知道哪里出了问题~

- 部署平台： **Cloudflare Pages**
- 部署后的地址：https://broadcastchannel-4cj.pages.dev/
- 创建的TG频道： https://t.me/s/random_bear
- fork后只修改了`.env.example`文件的`CHANNEL`字段为 **random_bear**

可是我尝试了好几次还是没有任何内容~如果您有时间的话，通过我上面的描述，可以看出来问题出在哪里吗~

---

**更新一下：可以直接把`.env.example`文件改成`.env`以后，在里面修改配置项内容即可。**

**Comment by ccbikai** [comment]
Fork 后不需要修改任何代码， 环境变量是通过部署平台修改的

Cloudflare Pages 的参考 https://developers.cloudflare.com/pages/functions/bindings/#environment-variables

To configure an environment variable via the Cloudflare dashboard:

Log in to the Cloudflare dashboard and select your account.
In Account Home, select Workers & Pages.
Select your Pages project > Settings > Environment variables.
Selecting Add variables under Production and/or Preview.
After setting a variable name and value, select Save.

修改完重新部署一下

**Comment by nicevlhjfihtqngkldl** [comment]
请问这个项目的效果是什么样的? 我在telegram channel发信息, 然后域名对应的网页会跟着更新,是这个效果吗?

**Comment by ccbikai** [comment]
> 请问这个项目的效果是什么样的? 我在telegram channel发信息, 然后域名对应的网页会跟着更新,是这个效果吗?

是的。

**Comment by ann61c** [comment]
我也遇到了相同的问题，经过排查之后发现并不是我 Environmental Variables 设置得不对。

猜测是因为我打开了 Restricting Saving Content, 所以它读取不到内容。 

我的 Telegram 频道在网页上无法直接打开，浏览器会提示跳转到 App 里，这个现象也印证了是因为 Restricting Saving Content. 

目前看来只要把 Restricting Saving Content 关闭即可正常显示频道内容。

**Comment by xchao0213** [comment]
> > name
> 
> 谢谢你的及时回复！已经成功部署了！非常好用~
> 
> 不过好奇后续会继续优化吗？我发现点击图片放大的效果会非常大，甚至图片会展示不全~

你的好了？我打不开你的网页

**Comment by ccbikai** [comment]
> > name
> 
> 谢谢你的及时回复！已经成功部署了！非常好用~
> 
> 不过好奇后续会继续优化吗？我发现点击图片放大的效果会非常大，甚至图片会展示不全~

图片会展示不全的问题修复了

**Comment by itpromiseland** [comment]
我是用vercel部署的，同样遇到网页正文是空白的情况，Restrict Saving Content那里也是关闭的，可是还是无法显示，不知道还有什么办法可以解决？

**Comment by itpromiseland** [comment]
这个网站会自动跟着tg频道更新吗？

**Comment by xchao0213** [comment]
> 这个网站会自动跟着tg频道更新吗？

https://t.me/s/yourChannelName 你直接打开这个网址看看，我是看了项目源码后发现的

**Comment by ccbikai** [comment]
> 这个网站会自动跟着tg频道更新吗？

会的

**Comment by ccbikai** [comment]
已经收录到常问问题  https://github.com/ccbikai/BroadcastChannel/blob/main/README.zh-cn.md#-%E5%B8%B8%E9%97%AE%E9%97%AE%E9%A2%98
