### ISSUE TITLE
频道推送与网页更新同步不及时

### ISSUE THREAD

**Issue by igeekshare** [ccbikai/BroadcastChannel#25]
昨天发的内容，网页今天还未更新过来，已经拉取最新版本了
网页：geekshare.org

**Comment by cxplay** [comment]
不显示的原因是你的频道的最新一条消息包含**引用格式**的文本, Telegram 的网页预览目前并不支持这种格式的消息, 所以没有显示.
> https://t.me/s/geekshare/4528

**Comment by cxplay** [comment]
不显示的原因是你的频道的最新一条消息包含**引用格式**的文本, Telegram 的网页预览目前并不支持这种格式的消息, 所以没有显示.
> https://t.me/s/geekshare/4528

**Comment by ccbikai** [comment]
目前还不支持同步 引用格式 ， 其他的同步都是正常的
