### ISSUE TITLE
希望增加一个功能,显示ID范围内的消息

### ISSUE THREAD

**Issue by leihao** [ccbikai/BroadcastChannel#28]
频道有一些内容是两三个消息共同说一个事情,但是单id显示不全,单before或者after又无法突出重点
希望可以参数同时接受before和after,然后按顺序显示

**Comment by ccbikai** [comment]
给个链接看看

**Comment by leihao** [comment]
https://broadcastchannel-a3r.pages.dev/after/10578
https://broadcastchannel-a3r.pages.dev/before/10581

https://t.me/LetITFlyW/10578
https://t.me/LetITFlyW/10579
https://t.me/LetITFlyW/10580

**Comment by ccbikai** [comment]
我试了一下， TG before和after 同时传的时候只有 before 生效
