### ISSUE TITLE
搜索「中文或数字」内容不一定能返回结果

### ISSUE THREAD

**Issue by picobird** [ccbikai/BroadcastChannel#29]
_虽然根据 ChatGPT 的推荐方法做了修改，但实际验证了一下并没有啥效果 😅_

在自己的和他人的站点做了测试发现搜索英文的基本上没什么问题
但输入中文或数字的时候返回的结果并不理想，有时候有结果，有时候没结果，
比如下图搜索“有趣”完全没结果，或者也可以试试“8220”
<img width="1678" alt="image" src="https://github.com/user-attachments/assets/3c71771d-624d-401c-9e91-2df063ab01ae">

在我自己的站点完全不返回结果

**Comment by ccbikai** [comment]
Telegram 的搜索问题很大，建议加 Tag

**Comment by tjsky** [comment]
因为这个搜索本质上还是`t.me\s\频道名`页面里的那个TG自己的搜索，并不支持中文分词

**Comment by GrassBlock1** [comment]
> Telegram 的搜索问题很大，建议加 Tag

Telegram 的搜索一时半会儿也不会对不支持分词的语言做支持，搜不到是正常现象。

感觉可以用 fuse.js（或者别的什么） + JSON 索引做一个搜索...可能的副作用就是建立索引的时间会变得特别长（我能想到的是递归获取信息）

比如说这样（虽然这样只能获取到一页的消息）：
https://github.com/GrassBlock1/TGChan2Microblog/blob/39866e7c2c788696c7d46fd916196db4e61f7b1c/src/pages/search/%5Bq%5D.astro#L25

**Comment by ccbikai** [comment]
最新版本支持使用谷歌站内搜索了

1. 提交你的 /sitemap.xml 到谷歌站长平台
2. 配置变量 GOOGLE_SEARCH_SITE=memo.miantiao.me/posts 后重新部署

谷歌索引很快，结束后就可以使用谷歌搜索了
