### ISSUE TITLE
静态proxy怎么弄？

### ISSUE THREAD

**Issue by govmoe** [ccbikai/BroadcastChannel#32]
默认情况是无法加载cdn5.telesco.pe的……但是我找不到怎么弄proxy反代。

**Comment by ccbikai** [comment]
添加了。更新下代码

这个资源是怎么产生的？

**Comment by govmoe** [comment]
> 添加了。更新下代码
> 
> 这个资源是怎么产生的？

默认情况下Static Proxy是没有的，这会加载不出来图片，但是我看其他站点都是xxx.com/static/https://cdn5.telesco.pe，能成功加载，不是很明白怎么弄的static proxy.

**Comment by ccbikai** [comment]
https://github.com/ccbikai/BroadcastChannel/commit/4f9a403c9018b708439721c3cd17b40a4a359e4a

**Comment by govmoe** [comment]
> [编号：4F9A403](https://github.com/ccbikai/BroadcastChannel/commit/4f9a403c9018b708439721c3cd17b40a4a359e4a)

👌
