### ISSUE TITLE
部署后空白

### ISSUE THREAD

**Issue by 5536086** [ccbikai/BroadcastChannel#34]
试了好几个公共频道，部署后都是空白，频道都符合文档要求，感觉兼容性应该是有一些问题的，望改进

**Comment by yhif** [comment]
CHANNEL要配置对，要写Invite Link斜杠后面的那个

**Comment by 5536086** [comment]
> CHANNEL要配置对，要写Invite Link斜杠后面的那个

成人向内容，都无法显示，不知道是不是屏蔽了

**Comment by ccbikai** [comment]
> > CHANNEL要配置对，要写Invite Link斜杠后面的那个
> 
> 成人向内容，都无法显示，不知道是不是屏蔽了

大概率被TG标记敏感了
