### ISSUE TITLE
前端不显示内容

### ISSUE THREAD

**Issue by trai25** [ccbikai/BroadcastChannel#38]
部署到cf pages了，但不知为啥，发的内容在rss里有，但前端空白，home 按钮和搜索框也不显示

https://broadcastchannel-di8.pages.dev/
https://broadcastchannel-di8.pages.dev/rss.xml

**Comment by ccbikai** [comment]
是不是时区配置了带引号的时区

**Comment by trai25** [comment]
> 是不是时区配置了带引号的时区
没有引号，我的变量 `TIMEZONE` 的值是 `Europe/​Berlin`

**Comment by ccbikai** [comment]
北京时间 使用 Asia/Shanghai 时区
