### ISSUE TITLE
Style error when having too many tags

### ISSUE THREAD

**Issue by nick-cjyx9** [ccbikai/BroadcastChannel#4]
![image](https://github.com/user-attachments/assets/b49b5420-7575-457b-ae2d-a61aeb9b03dc)

https://broadcastchannel.pages.dev/before/469

**Comment by ccbikai** [comment]
Repaired, try updating it.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui

**Comment by nick-cjyx9** [comment]
it disappears

![image](https://github.com/user-attachments/assets/a4a02d15-3b45-4a8c-acbc-b9746dd4fb67)

https://memos.nickchen.top/

**Comment by cyr580** [comment]
My tab bar disappeared too

**Comment by cyr580** [comment]
My tab bar disappeared too

**Comment by ccbikai** [comment]
Just now it was disconnected, and I've fixed it again. https://memo.miantiao.me/posts/113
