### ISSUE TITLE
code block 渲染問題

### ISSUE THREAD

**Issue by virgil724** [ccbikai/BroadcastChannel#40]
當你在telegram 上有用``` 去包裹code block
渲染的時候會壞掉
回報一下

**Comment by ccbikai** [comment]
方便提供一下频道吗？

**Comment by virgil724** [comment]
https://t.me/virgil246
https://mur.virgil246.com/

這邊提供channel和架設起來的網頁

**Comment by ccbikai** [comment]
已经修复，更新下代码确认下

**Comment by virgil724** [comment]
感謝修復 我這邊close issue囉
