### ISSUE TITLE
直接部署的，页面是空白，

### ISSUE THREAD

**Issue by yinqinghe** [ccbikai/BroadcastChannel#41]
或许，部署步骤没有看明白

**Comment by ccbikai** [comment]
CHANNEL 如何设置的？

**Comment by yinqinghe** [comment]
这样设置的
![image](https://github.com/user-attachments/assets/ef30ec46-385c-475b-b1b6-d1c86dd1a8ae)
原来的channel，也是空白

**Comment by ccbikai** [comment]
那个平台部署，截图一下部署平台环境变量设置， 应该不需要改本地文件

**Comment by yinqinghe** [comment]
我用的cloudfare部署的，平台环境变量设置是在那？
![Uploading image.png…]()

**Comment by yinqinghe** [comment]
平台环境变量是这里吗？
![image](https://github.com/user-attachments/assets/e6dc2998-a72d-471c-be1c-30add455fd88)

**Comment by ccbikai** [comment]
是的，是这边， 改完以后重新部署一下

**Comment by yinqinghe** [comment]
好的，可以了
