### ISSUE TITLE
不显示翻页按钮

### ISSUE THREAD

**Issue by wwng2333** [ccbikai/BroadcastChannel#42]
如题，部署地址为 https://fake-news.csgo.ovh 
环境变量：仅设置了频道名。
问题：只显示最新20条内容，更老的不显示，也没有`before`按钮

edit：手动添加`/before/14`后可以正常显示老旧内容，故修正问题为不显示翻页按钮

**Comment by ccbikai** [comment]
最新代码已经处理过，更新下代码

**Comment by wwng2333** [comment]
> 最新代码已经处理过，更新下代码。 如果还有问题重开下 issue

问题已解决
