### ISSUE TITLE
搜寻不支援中文

### ISSUE THREAD

**Issue by kuenwei** [ccbikai/BroadcastChannel#45]
刚刚尝试了一下，用中文当字词搜寻没有办法出现结果。

**Comment by ccbikai** [comment]
Telegram 目前对中文搜索不佳，可以提交网站到谷歌，使用谷歌的站内搜索

**Comment by 2ndMessiah** [comment]
> Telegram 目前对中文搜索不佳，可以提交网站到谷歌，使用谷歌的站内搜索

开发者您好，谢谢您的佳作。

请问如果想在google搜到网站里的内容，只需要在cse.google.com创建搜索引擎吗？ 创建了搜索引擎后，我试了在google搜site:xxxx.com（我的博客地址） keyword搜不出来东西。请问我这样操作对不对~

谢谢

**Comment by 2ndMessiah** [comment]
> > Telegram 目前对中文搜索不佳，可以提交网站到谷歌，使用谷歌的站内搜索
> 
> 开发者您好，谢谢您的佳作。
> 
> 请问如果想在google搜到网站里的内容，只需要在cse.google.com创建搜索引擎吗？ 创建了搜索引擎后，我试了在google搜“site:xxxx.com（我的博客地址） 关键字” 搜不出来东西。请问我这样操作对不对~ 我只是想自己搜自己发的笔记，因为tg搜索太烂。
> 
> 谢谢

**Comment by 2ndMessiah** [comment]
> https://search.google.com/search-console
> 
> 在这边认证域名，然后提交 Sitemap。 等一两天就行了

谢谢指导！请问是否可以直接插入谷歌搜索的javascript代码？在https://cse.google.com/里面创建了一个站内搜索引擎

**Comment by ccbikai** [comment]
我会尽快集成谷歌搜索，到时间你们只需要配置域名到环境变量即可

**Comment by ccbikai** [comment]
@kuenwei @2ndMessiah  已经可以通过 GOOGLE_SEARCH_SITE 变量来启用谷歌站内搜索了

可在 https://memo.miantiao.me/ 体验
