### ISSUE TITLE
音乐无法播放

### ISSUE THREAD

**Issue by SenLief** [ccbikai/BroadcastChannel#47]
Audio的类型，会跳转回tg的公告页面，这个有没有可能播放的？

**Comment by ccbikai** [comment]
帮忙提供下链接

**Comment by SenLief** [comment]
> 帮忙提供下链接

https://memo.zjan.me/posts/19

类型是audio，发送的形式为，直接拖入mp3文件广播的。

**Comment by sdlkhfksl** [comment]
音乐播放不了 视频可以

**Comment by ccbikai** [comment]
> > 帮忙提供下链接
> 
> https://memo.zjan.me/posts/19
> 
> 类型是audio，发送的形式为，直接拖入mp3文件广播的。

确认了一下，抓到的信息是没有音频链接的，暂时无法实现音乐播放
