### ISSUE TITLE
能否根据自定义的标签或者标题什么的来自定义tab页面

### ISSUE THREAD

**Issue by 3377** [ccbikai/BroadcastChannel#57]
如题，目前太乱了，写了一个rss指定内容推送到tg频道，很契合你的作品，但是没法自定义标签页，有点可惜。
`docker pull drfyup/rss2tg:latest`

**Comment by ccbikai** [comment]
推送的使用使用 # 加一下搜索标签，使用标签过滤呢

**Comment by ccbikai** [comment]
简单做了一个，可以先看下 

## 启用标签页, 标签使用英文逗号分割
TAGS=标签A,标签B,标签C

**Comment by 3377** [comment]
好的，感谢大佬。另外请教一下，页头和页尾的这个是指的在根目录建立两个html文件去编写吗？还是直接在这里写代码?
FOOTER_INJECT=FOOTER_INJECT
HEADER_INJECT=HEADER_INJECT

**Comment by ccbikai** [comment]
> 好的，感谢大佬。另外请教一下，页头和页尾的这个是指的在根目录建立两个html文件去编写吗？还是直接在这里写代码?
> 
> FOOTER_INJECT=FOOTER_INJECT
> 
> HEADER_INJECT=HEADER_INJECT

直接在 = 后面写一些简单的HTML代码就行

**Comment by 3377** [comment]
好的，感谢。需要双引号吗？

**Comment by ccbikai** [comment]
我这边没有写双引号
2024年11月4日 +0800 22:21 drfyup ***@***.***>，写道：
