### ISSUE TITLE
Messages with quotes won't show up.

### ISSUE THREAD

**Issue by GetToSet** [ccbikai/BroadcastChannel#58]
Looks like channel messages that contain quotes won't be picked up on the page.

You can add quoted text within the contextual menu as demonstrated below.

<img width="676" alt="Screenshot 2024-08-24 at 23 32 17" src="https://github.com/user-attachments/assets/9cc39a3f-9274-4901-b1c4-ef7ee13c21cf">

**Comment by ccbikai** [comment]
Quotes are currently not supported
