### ISSUE TITLE
【求助】作者有时间能帮我看下吗，空白呢

### ISSUE THREAD

**Issue by lolo1024** [ccbikai/BroadcastChannel#59]
最低配置部署在Vercel的，变量也设置了

**Comment by qcyh** [comment]
把 .env.example 文件名字改成 .env 就可以了

参考：https://github.com/ccbikai/BroadcastChannel/issues/2#issue-2447392928

**Comment by lolo1024** [comment]
还是没解决，甚至更，，，感觉步骤很简单呀，不知道哪里问题
![IMG_20240826_184529.jpg](https://github.com/user-attachments/assets/b72cf904-a44a-4ea6-90a1-5470a53cd6d8)

**Comment by qcyh** [comment]
那你试试重新 fork 一下项目，然后不修改原本的 .env.example，而是制作一个新的文件，命名为 “.env”，然后再在 “.env” 里面修改你的频道名等等呢？我就是这样操作的，也是在 vercel 部署的，成功了。

**Comment by ccbikai** [comment]
不需要修改文件，在 Vercel 管理界面配置  ENV 后，重新部署一下

**Comment by qcyh** [comment]
> 不需要修改文件，在 Vercel 管理界面配置 ENV 后，重新部署一下

刚刚去重新试了一下，部署成功了，谢谢！

**Comment by lolo1024** [comment]
重新fork后还是不信呢，问题可能出现在env上？
CHANNEL后面的值可以给我个示例吗？比如我的频道是t.me/lolo2048

**Comment by lolo1024** [comment]
求分享，我觉得我跟个白痴一样> > 不需要修改文件，在 Vercel 管理界面配置 ENV 后，重新部署一下
> 
> 刚刚去重新试了一下，部署成功了，谢谢！

**Comment by qcyh** [comment]
> 重新fork后还是不信呢，问题可能出现在env上？ CHANNEL后面的值可以给我个示例吗？比如我的频道是t.me/lolo2048

CHANNEL 后面的值就写：lolo2048（CHANNEL=lolo2048）

根据刚刚作者的解答，在 fork 之后，不用修改任何文件，你可以直接在 vercel 部署的时候，在 environment 那里去设置这三个项目就行：

![image-20240826191600857](https://github.com/user-attachments/assets/55b57948-6a6d-4343-8095-d50f583321fd)

**Comment by lolo1024** [comment]
还是不行，给您截图看一下，我这里还出现第三种错误，主页显示HEADER和FOOTER
![IMG_20240826_184529.jpg](https://github.com/user-attachments/assets/38206755-be15-417c-936c-1b151b1ebcdd)
env我也按照你的设置后重新部署
![IMG_20240826_192859.jpg](https://github.com/user-attachments/assets/dfe1ceae-3010-42b1-9d7b-553790a97930)



> 把 .env.example 文件名字改成 .env 就可以了
> 
> 参考：https://github.com/ccbikai/BroadcastChannel/issues/2#issue-2447392928

**Comment by qcyh** [comment]
> 还是不行，给您截图看一下，我这里还出现第三种错误，主页显示HEADER和FOOTER ![IMG_20240826_184529.jpg](https://private-user-images.githubusercontent.com/73373465/361416648-38206755-be15-417c-936c-1b151b1ebcdd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzODgsIm5iZiI6MTcyNDY3MjA4OCwicGF0aCI6Ii83MzM3MzQ2NS8zNjE0MTY2NDgtMzgyMDY3NTUtYmUxNS00MTdjLTkzNmMtMWIxNTFiMWViY2RkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMDVkZjM0MzhlMzc5ZTlhOTcyYzYxMWFkYWNhYjM4M2IzY2Q1YjI1Mzc5OTZlZDU5ODY5YTdlMTAwY2FlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbxlyRK-UXK7YryU8IraizFr9R7MN30dLcq3Aum5WyU) env我也按照你的设置后重新部署 ![IMG_20240826_192859.jpg](https://private-user-images.githubusercontent.com/73373465/361416755-dfe1ceae-3010-42b1-9d7b-553790a97930.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzODgsIm5iZiI6MTcyNDY3MjA4OCwicGF0aCI6Ii83MzM3MzQ2NS8zNjE0MTY3NTUtZGZlMWNlYWUtMzAxMC00MmIxLTlkN2ItNTUzNzkwYTk3OTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2U4ODk2ZjBkNzhiYmIwYTI3MDc0NTcxYTE4MmEzMGM1MmMyYWVkNDZlMzc0OTBkNWU0ZGE0MzUxOWEwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDNUd6ZpRNg1uEVFXo8nSXU4A071Cl1odqZmcfVKYn4)
> 
> > 把 .env.example 文件名字改成 .env 就可以了
> > 参考：[#2 (comment)](https://github.com/ccbikai/BroadcastChannel/issues/2#issue-2447392928)

你把仓库里面的 .env 删除掉，只在 Vercel 里面按照上面图中设置的那样设置就好

**Comment by lolo1024** [comment]
正好正常了，频道发了测试消息还没同步过来，同步是多久同步一次

**Comment by lolo1024** [comment]
还有就是频道Restricting saving content设置项在哪里

**Comment by lolo1024** [comment]
求解惑🥺> > 还是不行，给您截图看一下，我这里还出现第三种错误，主页显示HEADER和FOOTER ![IMG_20240826_184529.jpg](https://private-user-images.githubusercontent.com/73373465/361416648-38206755-be15-417c-936c-1b151b1ebcdd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzODgsIm5iZiI6MTcyNDY3MjA4OCwicGF0aCI6Ii83MzM3MzQ2NS8zNjE0MTY2NDgtMzgyMDY3NTUtYmUxNS00MTdjLTkzNmMtMWIxNTFiMWViY2RkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMDVkZjM0MzhlMzc5ZTlhOTcyYzYxMWFkYWNhYjM4M2IzY2Q1YjI1Mzc5OTZlZDU5ODY5YTdlMTAwY2FlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbxlyRK-UXK7YryU8IraizFr9R7MN30dLcq3Aum5WyU) env我也按照你的设置后重新部署 ![IMG_20240826_192859.jpg](https://private-user-images.githubusercontent.com/73373465/361416755-dfe1ceae-3010-42b1-9d7b-553790a97930.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzODgsIm5iZiI6MTcyNDY3MjA4OCwicGF0aCI6Ii83MzM3MzQ2NS8zNjE0MTY3NTUtZGZlMWNlYWUtMzAxMC00MmIxLTlkN2ItNTUzNzkwYTk3OTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2U4ODk2ZjBkNzhiYmIwYTI3MDc0NTcxYTE4MmEzMGM1MmMyYWVkNDZlMzc0OTBkNWU0ZGE0MzUxOWEwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDNUd6ZpRNg1uEVFXo8nSXU4A071Cl1odqZmcfVKYn4)
> > 
> > > 把 .env.example 文件名字改成 .env 就可以了
> > > 参考：[#2 (comment)](https://github.com/ccbikai/BroadcastChannel/issues/2#issue-2447392928)
> 
> 你把仓库里面的 .env 删除掉，只在 Vercel 里面按照上面图中设置的那样设置就好
