### ISSUE TITLE
【求助】为什么我的项目不能正常搜索，只能搜索标签呢

### ISSUE THREAD

**Issue by lolo1024** [ccbikai/BroadcastChannel#65]
如题
网址:https://blog.0520.com.cn
麻烦帮忙看下https://github.com/lolo1024/BroadcastChannel

**Comment by lolo1024** [comment]
我发现我的频道在tg里也无法搜索关键字呢，这是什么原因，，，

**Comment by ccbikai** [comment]
TG 对中文的搜索很差
