### ISSUE TITLE
部署后一片空白，CF 变量有设置

### ISSUE THREAD

**Issue by thedavidweng** [ccbikai/BroadcastChannel#67]
https://davybao.pages.dev/
部署后一片空白，CF 变量有设置
<img width="972" alt="Screenshot 2024-09-19 at 2 08 17 PM" src="https://github.com/user-attachments/assets/1ff046f2-2090-41e1-9fd2-b1722f051da4">
好奇怪呢

**Comment by ccbikai** [comment]
修改完环境变量后是否重新部署过？

**Comment by thedavidweng** [comment]
> 修改完环境变量后是否重新部署过？

有的，而且我的 Fork 设置了自动 sync 上游，每次上游更新都会重新部署。
这个之前是正常的，放着不管一段时间后就这样了。

**Comment by ccbikai** [comment]
https://t.me/s/davybao

应该是你账号被 TG 标记，或者你关了转发了

**Comment by thedavidweng** [comment]
> https://t.me/s/davybao
> 
> 应该是你账号被 TG 标记，或者你关了转发了

我都不知道怎么关转发，账户被标记这个请问有我可以 look into 的信息吗

**Comment by ccbikai** [comment]
频道被 TG 禁止转发以后，好像没办法开启，可换一个或者联系 TG
