### ISSUE TITLE
Is it possible to add interactive feature in web?

### ISSUE THREAD

**Issue by 4t8dd** [ccbikai/BroadcastChannel#72]
The content is sent from channel, and readers can read from web.
But only reading make it not outstanding. Have you ever consider to add some interactive feature in the web? Like
emoji, comments. Maybe emoji is enough for this short message, like, flower, likes or dislikes. 

Just my thoughts.

**Comment by ccbikai** [comment]
TG's comment function may be added

**Comment by ccbikai** [comment]
Setting the environment variable COMMENTS=true and redeploying will enable comments
