### ISSUE TITLE
能否实现加一个标签聚合~？

### ISSUE THREAD

**Issue by 2ndMessiah** [ccbikai/BroadcastChannel#78]
Hi Dev，

这样更有利于整理分类。不是是否好实现。

谢谢！

**Comment by ccbikai** [comment]
目前没有自动获取标签的方案。最新版本可以手动设置一个标签页面

如下方式配置环境变量
```
## 启用标签页, 标签使用英文逗号分割
TAGS=标签A,标签B,标签C
```

**Comment by 2ndMessiah** [comment]
> 目前没有自动获取标签的方案。最新版本可以手动设置一个标签页面
> 
> 
> 
> 如下方式配置环境变量
> 
> ```
> 
> ## 启用标签页, 标签使用英文逗号分割
> 
> TAGS=标签A,标签B,标签C
> 
> ```

辛苦了😭😭太感谢了
