### ISSUE TITLE
有的公开频道不能通过https://t.me/s/ 预览

### ISSUE THREAD

**Issue by nbtu** [ccbikai/BroadcastChannel#9]
我看日志项目是通过https://t.me/s/获取频道内容，但我发现有的公开频道不能通过https://t.me/s/88888 预览，会直接跳到https://t.me/88888 提示客户端/网页打开，这种频道部署后会显示空吧，不知道这个预览有什么规则？

**Comment by itpromiseland** [comment]
确实会显示空网页，可能是你的频道被标记了，存在什么不当内容，我的频道就是这样的，所以后来我换了一个频道就正常了。

**Comment by BlueSkyXN** [comment]
可惜不支持私有频道
你那个估计是判定为色情了，所以要授权

**Comment by ccbikai** [comment]
Telegram 限制敏感频道不能预览，可以搜索下具体细节
